### ISSUE TITLE
UndefVarError: P not defined

### ISSUE THREAD

**Issue by dfernandezfraile** [felipenoris/BLPData.jl#18]
Hi, thanks for this software.

I am getting this error when trying the example of call to BLPData.bdh:

DataFrame( BLPData.bdh(session, "PETR4 BS Equity", ["PX_LAST", "VOLUME"], Date(2020, 1, 2), Date(2020, 1, 10) ))

UndefVarError: P not defined

Stacktrace:
  [1] Date(blp_datetime::BLPData.BLPDateTime)
    @ BLPData ~/.julia/packages/BLPData/pXEwo/src/datetime.jl:25
...

I could circumvent it by commenting out the line 25, so it avoids that check. But I am sure there could be a better way of fixing that.

Thank you very much.

**Comment by felipenoris** [comment]
You are completely right!
This is a bug. Looks like Bloomberg started to set the `OFFSET` flag on their date time struct. This is now corrected.
Thanks!
